name: Build Freenove Board

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build freenove-esp32s3-display-2.8-lcd
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v6.0.2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          source $IDF_PATH/export.sh
          python scripts/build.py freenove-esp32s3-display-2.8-lcd --name freenove-esp32s3-display-2.8-lcd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: xiaozhi_freenove-esp32s3-display-2.8-lcd
          path: build/merged-binary.bin
          if-no-files-found: error
